// Generates sw.js: derives the precache list from what the pages actually
// reference and stamps a content-hash version. Run: node build-sw.js
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = __dirname;
const PAGES = ['index.html', 'anki.html'];

// Every local asset the pages pull in via href/src, plus the pages and root.
function referenced() {
  const out = new Set(['./']);
  for (const page of PAGES) {
    out.add(page);
    const html = fs.readFileSync(path.join(ROOT, page), 'utf8');
    for (const m of html.matchAll(/(?:href|src)="([^"]+)"/g)) {
      const u = m[1];
      if (!/^(https?:|data:|#|mailto:)/.test(u)) out.add(u);
    }
  }
  out.add('manifest.webmanifest');
  const mani = JSON.parse(fs.readFileSync(path.join(ROOT, 'manifest.webmanifest'), 'utf8'));
  for (const ic of mani.icons || []) out.add(ic.src);
  return [...out].sort();
}

const ASSETS = referenced();

// Hash the real files so the version changes iff a cached asset changes.
function version() {
  const h = crypto.createHash('sha256');
  for (const a of ASSETS) {
    if (a === './') continue;
    h.update(a);
    h.update(fs.readFileSync(path.join(ROOT, a)));
  }
  return 'anki-' + h.digest('hex').slice(0, 8);
}

function buildSW() {
  return `// GENERATED by build-sw.js — do not edit. Run: node build-sw.js
const CACHE = ${JSON.stringify(version())};
const ASSETS = ${JSON.stringify(ASSETS, null, 2)};

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// cache-first for same-origin GETs; navigations fall back to the cached shell
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  }).catch(() => req.mode === 'navigate' ? caches.match('./') : Response.error())));
});
`;
}

if (require.main === module) {
  fs.writeFileSync(path.join(ROOT, 'sw.js'), buildSW());
  console.log('wrote sw.js', version(), '·', ASSETS.length, 'assets');
}

module.exports = { ASSETS, version, buildSW };
