// Build: bundle+hash JS/CSS via esbuild, hash icons, rewrite manifest + HTML.
// Output to dist/. Service worker is added in a later step.
import esbuild from 'esbuild';
import crypto from 'node:crypto';
import path from 'node:path';
import {
  rmSync, mkdirSync, readFileSync, writeFileSync, renameSync, readdirSync,
} from 'node:fs';

const ROOT = import.meta.dirname;
const SRC = path.join(ROOT, 'src');
const DIST = path.join(ROOT, 'dist');
const PAGES = ['index.html', 'anki.html', 'vocab.html'];
const ICONS = ['icon-192.png', 'icon-512.png', 'icon.svg', 'apple-touch-icon.png'];

const hash8 = buf => crypto.createHash('sha256').update(buf).digest('hex').slice(0, 8);

// "name.ext" -> "name-<hash>.ext"
function hashedName(name, buf) {
  const ext = path.extname(name);
  return `${name.slice(0, -ext.length)}-${hash8(buf)}${ext}`;
}

function cleanDist() {
  rmSync(DIST, { recursive: true, force: true });
  mkdirSync(DIST, { recursive: true });
}

// Bundle + minify the page entries and stylesheet, then sha256-hash the outputs.
async function bundleCode() {
  const { metafile } = await esbuild.build({
    entryPoints: [
      path.join(SRC, 'script.js'),
      path.join(SRC, 'anki.js'),
      path.join(SRC, 'vocab.js'),
      path.join(SRC, 'style.css'),
    ],
    bundle: true, minify: true, format: 'esm',
    outdir: DIST, metafile: true,
  });
  const map = {};
  for (const [out, meta] of Object.entries(metafile.outputs)) {
    if (!meta.entryPoint) continue;
    const buf = readFileSync(out);
    const hashed = hashedName(path.basename(out), buf);
    renameSync(out, path.join(DIST, hashed));
    map[path.basename(meta.entryPoint)] = hashed;
  }
  return map;
}

// Copy each icon under a content-hashed name; return {original: hashed}.
function hashIcons() {
  const map = {};
  for (const ic of ICONS) {
    const buf = readFileSync(path.join(SRC, ic));
    const out = hashedName(ic, buf);
    writeFileSync(path.join(DIST, out), buf);
    map[ic] = out;
  }
  return map;
}

// Rewrite manifest icon srcs to hashed names; emit it content-hashed too.
function buildManifest(iconMap) {
  const mani = JSON.parse(readFileSync(path.join(SRC, 'manifest.webmanifest'), 'utf8'));
  for (const ic of mani.icons || []) if (iconMap[ic.src]) ic.src = iconMap[ic.src];
  const json = JSON.stringify(mani, null, 2);
  const out = hashedName('manifest.webmanifest', Buffer.from(json));
  writeFileSync(path.join(DIST, out), json);
  return out;
}

// Rewrite every local href/src in a page to its hashed output name.
function buildHtml(page, refMap) {
  const html = readFileSync(path.join(SRC, page), 'utf8')
    .replace(/(href|src)="([^"]+)"/g, (m, attr, url) =>
      refMap[url] ? `${attr}="${refMap[url]}"` : m);
  writeFileSync(path.join(DIST, page), html);
}

// Precache every built file plus the pages and root; cache key tracks content.
function buildSW() {
  const assets = readdirSync(DIST).filter(f => f !== 'sw.js');
  const list = ['./', ...assets].sort();
  const version = 'anki-' + hash8(Buffer.from(list.join('|')));
  const sw = `// GENERATED by build.js — do not edit. Run: node build.js
const CACHE = ${JSON.stringify(version)};
const ASSETS = ${JSON.stringify(list, null, 2)};

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// network-first for navigations (fresh HTML); cache-first for hashed assets
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req)
      .then(res => { const c = res.clone(); caches.open(CACHE).then(x => x.put(req, c)); return res; })
      .catch(() => caches.match(req).then(hit => hit || caches.match('./'))));
    return;
  }
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
    if (res.ok) { const c = res.clone(); caches.open(CACHE).then(x => x.put(req, c)); }
    return res;
  })));
});
`;
  writeFileSync(path.join(DIST, 'sw.js'), sw);
  return { version, assets: list };
}

export async function build() {
  cleanDist();
  const codeMap = await bundleCode();
  const iconMap = hashIcons();
  const manifest = buildManifest(iconMap);
  const refMap = { ...codeMap, ...iconMap, 'manifest.webmanifest': manifest };
  for (const page of PAGES) buildHtml(page, refMap);
  const sw = buildSW();
  return { refMap, ...sw };
}

import { realpathSync } from 'node:fs';
const isMain = process.argv[1] && realpathSync(process.argv[1]) === import.meta.filename;
if (isMain) {
  await build();
  console.log('built dist/ ·', readdirSync(DIST).length, 'files');
  if (process.argv.includes('--watch')) {
    const { watch } = await import('node:fs');
    let timer = null;
    watch(SRC, { recursive: true }, () => {
      clearTimeout(timer);
      timer = setTimeout(() => build().then(() => console.log('rebuilt')), 100);
    });
    console.log('watching src/ …');
  }
}
