// 五十音 data + pure rōmaji match. Shared by browser and node tests.

const KANA = [
  // gojūon
  { id: 'a',  hira: 'あ', kata: 'ア', romaji: 'a',  aliases: [], group: 'gojuon' },
  { id: 'i',  hira: 'い', kata: 'イ', romaji: 'i',  aliases: [], group: 'gojuon' },
  { id: 'u',  hira: 'う', kata: 'ウ', romaji: 'u',  aliases: [], group: 'gojuon' },
  { id: 'e',  hira: 'え', kata: 'エ', romaji: 'e',  aliases: [], group: 'gojuon' },
  { id: 'o',  hira: 'お', kata: 'オ', romaji: 'o',  aliases: [], group: 'gojuon' },
  { id: 'ka', hira: 'か', kata: 'カ', romaji: 'ka', aliases: [], group: 'gojuon' },
  { id: 'ki', hira: 'き', kata: 'キ', romaji: 'ki', aliases: [], group: 'gojuon' },
  { id: 'ku', hira: 'く', kata: 'ク', romaji: 'ku', aliases: [], group: 'gojuon' },
  { id: 'ke', hira: 'け', kata: 'ケ', romaji: 'ke', aliases: [], group: 'gojuon' },
  { id: 'ko', hira: 'こ', kata: 'コ', romaji: 'ko', aliases: [], group: 'gojuon' },
  { id: 'sa',  hira: 'さ', kata: 'サ', romaji: 'sa',  aliases: [],     group: 'gojuon' },
  { id: 'shi', hira: 'し', kata: 'シ', romaji: 'shi', aliases: ['si'], group: 'gojuon' },
  { id: 'su',  hira: 'す', kata: 'ス', romaji: 'su',  aliases: [],     group: 'gojuon' },
  { id: 'se',  hira: 'せ', kata: 'セ', romaji: 'se',  aliases: [],     group: 'gojuon' },
  { id: 'so',  hira: 'そ', kata: 'ソ', romaji: 'so',  aliases: [],     group: 'gojuon' },
  { id: 'ta',  hira: 'た', kata: 'タ', romaji: 'ta',  aliases: [],     group: 'gojuon' },
  { id: 'chi', hira: 'ち', kata: 'チ', romaji: 'chi', aliases: ['ti'], group: 'gojuon' },
  { id: 'tsu', hira: 'つ', kata: 'ツ', romaji: 'tsu', aliases: ['tu'], group: 'gojuon' },
  { id: 'te',  hira: 'て', kata: 'テ', romaji: 'te',  aliases: [],     group: 'gojuon' },
  { id: 'to',  hira: 'と', kata: 'ト', romaji: 'to',  aliases: [],     group: 'gojuon' },
  { id: 'na', hira: 'な', kata: 'ナ', romaji: 'na', aliases: [], group: 'gojuon' },
  { id: 'ni', hira: 'に', kata: 'ニ', romaji: 'ni', aliases: [], group: 'gojuon' },
  { id: 'nu', hira: 'ぬ', kata: 'ヌ', romaji: 'nu', aliases: [], group: 'gojuon' },
  { id: 'ne', hira: 'ね', kata: 'ネ', romaji: 'ne', aliases: [], group: 'gojuon' },
  { id: 'no', hira: 'の', kata: 'ノ', romaji: 'no', aliases: [], group: 'gojuon' },
  { id: 'ha', hira: 'は', kata: 'ハ', romaji: 'ha', aliases: [],     group: 'gojuon' },
  { id: 'hi', hira: 'ひ', kata: 'ヒ', romaji: 'hi', aliases: [],     group: 'gojuon' },
  { id: 'fu', hira: 'ふ', kata: 'フ', romaji: 'fu', aliases: ['hu'], group: 'gojuon' },
  { id: 'he', hira: 'へ', kata: 'ヘ', romaji: 'he', aliases: [],     group: 'gojuon' },
  { id: 'ho', hira: 'ほ', kata: 'ホ', romaji: 'ho', aliases: [],     group: 'gojuon' },
  { id: 'ma', hira: 'ま', kata: 'マ', romaji: 'ma', aliases: [], group: 'gojuon' },
  { id: 'mi', hira: 'み', kata: 'ミ', romaji: 'mi', aliases: [], group: 'gojuon' },
  { id: 'mu', hira: 'む', kata: 'ム', romaji: 'mu', aliases: [], group: 'gojuon' },
  { id: 'me', hira: 'め', kata: 'メ', romaji: 'me', aliases: [], group: 'gojuon' },
  { id: 'mo', hira: 'も', kata: 'モ', romaji: 'mo', aliases: [], group: 'gojuon' },
  { id: 'ya', hira: 'や', kata: 'ヤ', romaji: 'ya', aliases: [], group: 'gojuon' },
  { id: 'yu', hira: 'ゆ', kata: 'ユ', romaji: 'yu', aliases: [], group: 'gojuon' },
  { id: 'yo', hira: 'よ', kata: 'ヨ', romaji: 'yo', aliases: [], group: 'gojuon' },
  { id: 'ra', hira: 'ら', kata: 'ラ', romaji: 'ra', aliases: [], group: 'gojuon' },
  { id: 'ri', hira: 'り', kata: 'リ', romaji: 'ri', aliases: [], group: 'gojuon' },
  { id: 'ru', hira: 'る', kata: 'ル', romaji: 'ru', aliases: [], group: 'gojuon' },
  { id: 're', hira: 'れ', kata: 'レ', romaji: 're', aliases: [], group: 'gojuon' },
  { id: 'ro', hira: 'ろ', kata: 'ロ', romaji: 'ro', aliases: [], group: 'gojuon' },
  { id: 'wa', hira: 'わ', kata: 'ワ', romaji: 'wa', aliases: [],    group: 'gojuon' },
  { id: 'wo', hira: 'を', kata: 'ヲ', romaji: 'wo', aliases: ['o'], group: 'gojuon' },
  { id: 'n',  hira: 'ん', kata: 'ン', romaji: 'n',  aliases: ['nn'], group: 'gojuon' },

  // dakuten / handakuten
  { id: 'ga', hira: 'が', kata: 'ガ', romaji: 'ga', aliases: [], group: 'dakuten' },
  { id: 'gi', hira: 'ぎ', kata: 'ギ', romaji: 'gi', aliases: [], group: 'dakuten' },
  { id: 'gu', hira: 'ぐ', kata: 'グ', romaji: 'gu', aliases: [], group: 'dakuten' },
  { id: 'ge', hira: 'げ', kata: 'ゲ', romaji: 'ge', aliases: [], group: 'dakuten' },
  { id: 'go', hira: 'ご', kata: 'ゴ', romaji: 'go', aliases: [], group: 'dakuten' },
  { id: 'za', hira: 'ざ', kata: 'ザ', romaji: 'za', aliases: [],     group: 'dakuten' },
  { id: 'ji', hira: 'じ', kata: 'ジ', romaji: 'ji', aliases: ['zi'], group: 'dakuten' },
  { id: 'zu', hira: 'ず', kata: 'ズ', romaji: 'zu', aliases: [],     group: 'dakuten' },
  { id: 'ze', hira: 'ぜ', kata: 'ゼ', romaji: 'ze', aliases: [],     group: 'dakuten' },
  { id: 'zo', hira: 'ぞ', kata: 'ゾ', romaji: 'zo', aliases: [],     group: 'dakuten' },
  { id: 'da',  hira: 'だ', kata: 'ダ', romaji: 'da', aliases: [],     group: 'dakuten' },
  { id: 'dji', hira: 'ぢ', kata: 'ヂ', romaji: 'ji', aliases: ['di'], group: 'dakuten' },
  { id: 'dzu', hira: 'づ', kata: 'ヅ', romaji: 'zu', aliases: ['du'], group: 'dakuten' },
  { id: 'de',  hira: 'で', kata: 'デ', romaji: 'de', aliases: [],     group: 'dakuten' },
  { id: 'do',  hira: 'ど', kata: 'ド', romaji: 'do', aliases: [],     group: 'dakuten' },
  { id: 'ba', hira: 'ば', kata: 'バ', romaji: 'ba', aliases: [], group: 'dakuten' },
  { id: 'bi', hira: 'び', kata: 'ビ', romaji: 'bi', aliases: [], group: 'dakuten' },
  { id: 'bu', hira: 'ぶ', kata: 'ブ', romaji: 'bu', aliases: [], group: 'dakuten' },
  { id: 'be', hira: 'べ', kata: 'ベ', romaji: 'be', aliases: [], group: 'dakuten' },
  { id: 'bo', hira: 'ぼ', kata: 'ボ', romaji: 'bo', aliases: [], group: 'dakuten' },
  { id: 'pa', hira: 'ぱ', kata: 'パ', romaji: 'pa', aliases: [], group: 'dakuten' },
  { id: 'pi', hira: 'ぴ', kata: 'ピ', romaji: 'pi', aliases: [], group: 'dakuten' },
  { id: 'pu', hira: 'ぷ', kata: 'プ', romaji: 'pu', aliases: [], group: 'dakuten' },
  { id: 'pe', hira: 'ぺ', kata: 'ペ', romaji: 'pe', aliases: [], group: 'dakuten' },
  { id: 'po', hira: 'ぽ', kata: 'ポ', romaji: 'po', aliases: [], group: 'dakuten' },

  // yōon
  { id: 'kya', hira: 'きゃ', kata: 'キャ', romaji: 'kya', aliases: [], group: 'yoon' },
  { id: 'kyu', hira: 'きゅ', kata: 'キュ', romaji: 'kyu', aliases: [], group: 'yoon' },
  { id: 'kyo', hira: 'きょ', kata: 'キョ', romaji: 'kyo', aliases: [], group: 'yoon' },
  { id: 'sha', hira: 'しゃ', kata: 'シャ', romaji: 'sha', aliases: ['sya'], group: 'yoon' },
  { id: 'shu', hira: 'しゅ', kata: 'シュ', romaji: 'shu', aliases: ['syu'], group: 'yoon' },
  { id: 'sho', hira: 'しょ', kata: 'ショ', romaji: 'sho', aliases: ['syo'], group: 'yoon' },
  { id: 'cha', hira: 'ちゃ', kata: 'チャ', romaji: 'cha', aliases: ['tya'], group: 'yoon' },
  { id: 'chu', hira: 'ちゅ', kata: 'チュ', romaji: 'chu', aliases: ['tyu'], group: 'yoon' },
  { id: 'cho', hira: 'ちょ', kata: 'チョ', romaji: 'cho', aliases: ['tyo'], group: 'yoon' },
  { id: 'nya', hira: 'にゃ', kata: 'ニャ', romaji: 'nya', aliases: [], group: 'yoon' },
  { id: 'nyu', hira: 'にゅ', kata: 'ニュ', romaji: 'nyu', aliases: [], group: 'yoon' },
  { id: 'nyo', hira: 'にょ', kata: 'ニョ', romaji: 'nyo', aliases: [], group: 'yoon' },
  { id: 'hya', hira: 'ひゃ', kata: 'ヒャ', romaji: 'hya', aliases: [], group: 'yoon' },
  { id: 'hyu', hira: 'ひゅ', kata: 'ヒュ', romaji: 'hyu', aliases: [], group: 'yoon' },
  { id: 'hyo', hira: 'ひょ', kata: 'ヒョ', romaji: 'hyo', aliases: [], group: 'yoon' },
  { id: 'mya', hira: 'みゃ', kata: 'ミャ', romaji: 'mya', aliases: [], group: 'yoon' },
  { id: 'myu', hira: 'みゅ', kata: 'ミュ', romaji: 'myu', aliases: [], group: 'yoon' },
  { id: 'myo', hira: 'みょ', kata: 'ミョ', romaji: 'myo', aliases: [], group: 'yoon' },
  { id: 'rya', hira: 'りゃ', kata: 'リャ', romaji: 'rya', aliases: [], group: 'yoon' },
  { id: 'ryu', hira: 'りゅ', kata: 'リュ', romaji: 'ryu', aliases: [], group: 'yoon' },
  { id: 'ryo', hira: 'りょ', kata: 'リョ', romaji: 'ryo', aliases: [], group: 'yoon' },
  { id: 'gya', hira: 'ぎゃ', kata: 'ギャ', romaji: 'gya', aliases: [], group: 'yoon' },
  { id: 'gyu', hira: 'ぎゅ', kata: 'ギュ', romaji: 'gyu', aliases: [], group: 'yoon' },
  { id: 'gyo', hira: 'ぎょ', kata: 'ギョ', romaji: 'gyo', aliases: [], group: 'yoon' },
  { id: 'ja',  hira: 'じゃ', kata: 'ジャ', romaji: 'ja',  aliases: ['jya'], group: 'yoon' },
  { id: 'ju',  hira: 'じゅ', kata: 'ジュ', romaji: 'ju',  aliases: ['jyu'], group: 'yoon' },
  { id: 'jo',  hira: 'じょ', kata: 'ジョ', romaji: 'jo',  aliases: ['jyo'], group: 'yoon' },
  { id: 'bya', hira: 'びゃ', kata: 'ビャ', romaji: 'bya', aliases: [], group: 'yoon' },
  { id: 'byu', hira: 'びゅ', kata: 'ビュ', romaji: 'byu', aliases: [], group: 'yoon' },
  { id: 'byo', hira: 'びょ', kata: 'ビョ', romaji: 'byo', aliases: [], group: 'yoon' },
  { id: 'pya', hira: 'ぴゃ', kata: 'ピャ', romaji: 'pya', aliases: [], group: 'yoon' },
  { id: 'pyu', hira: 'ぴゅ', kata: 'ピュ', romaji: 'pyu', aliases: [], group: 'yoon' },
  { id: 'pyo', hira: 'ぴょ', kata: 'ピョ', romaji: 'pyo', aliases: [], group: 'yoon' },
];

// Grid placement. null = empty cell. Each inner array is one top-to-bottom
// column; dakuten/handakuten columns line up under their gojūon base.
const EMPTY = [null, null, null, null, null];
const LAYOUT = {
  //     a     ka    sa    ta    na    ha    ma    ya    ra    wa    n
  gojuon: [
    ['a',  'i',  'u',  'e',  'o'],
    ['ka', 'ki', 'ku', 'ke', 'ko'],
    ['sa', 'shi','su', 'se', 'so'],
    ['ta', 'chi','tsu','te', 'to'],
    ['na', 'ni', 'nu', 'ne', 'no'],
    ['ha', 'hi', 'fu', 'he', 'ho'],
    ['ma', 'mi', 'mu', 'me', 'mo'],
    ['ya', null, 'yu', null, 'yo'],
    ['ra', 'ri', 'ru', 're', 'ro'],
    ['wa', null, null, null, 'wo'],
    ['n',  null, null, null, null],
  ],
  // voiced rows under ka/sa/ta/ha; pa rides left of ba to skip a row band
  dakuten: [
    EMPTY,
    ['ga', 'gi',  'gu',  'ge', 'go'],
    ['za', 'ji',  'zu',  'ze', 'zo'],
    ['da', 'dji', 'dzu', 'de', 'do'],
    EMPTY,
    ['ba', 'bi',  'bu',  'be', 'bo'],
    ['pa', 'pi',  'pu',  'pe', 'po'],
    EMPTY, EMPTY, EMPTY, EMPTY,
  ],
  yoon: [
    ['kya', 'kyu', 'kyo'],
    ['sha', 'shu', 'sho'],
    ['cha', 'chu', 'cho'],
    ['nya', 'nyu', 'nyo'],
    ['hya', 'hyu', 'hyo'],
    ['mya', 'myu', 'myo'],
    ['rya', 'ryu', 'ryo'],
    ['gya', 'gyu', 'gyo'],
    ['ja',  'ju',  'jo'],
    ['bya', 'byu', 'byo'],
    ['pya', 'pyu', 'pyo'],
  ],
};

// Case-insensitive prefix match on romaji + aliases. Empty query = no match.
function matchRomaji(query, entry) {
  const q = (query || '').trim().toLowerCase();
  if (!q) return false;
  if (entry.romaji.startsWith(q)) return true;
  return entry.aliases.some(a => a.startsWith(q));
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { KANA, LAYOUT, matchRomaji };
}
