// GENERATED by build-sw.js — do not edit. Run: node build-sw.js
const CACHE = "anki-e911dcde";
const ASSETS = [
  "./",
  "anki.html",
  "anki.js",
  "apple-touch-icon.png",
  "fsrs.js",
  "icon-192.png",
  "icon-512.png",
  "icon.svg",
  "index.html",
  "kana.js",
  "manifest.webmanifest",
  "pwa.js",
  "script.js",
  "stats.js",
  "style.css"
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// cache-first for same-origin GETs; navigations fall back to the cached shell
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  }).catch(() => req.mode === 'navigate' ? caches.match('./') : Response.error())));
});
