import fs from 'node:fs';
import path from 'node:path';
import { alignFurigana } from '../src/furigana.js';

const FILES = [['n5.csv', 'N5'], ['n4.csv', 'N4'], ['n3.csv', 'N3'],
  ['n2.csv', 'N2'], ['n1.csv', 'N1']];
const RANK = { N5: 0, N4: 1, N3: 2, N2: 3, N1: 4 };  // lower = easier

// Minimal RFC-4180-ish CSV: quoted fields with commas + "" escapes.
export function parseCsv(text) {
  const rows = []; let row = [], field = '', q = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (q) {
      if (c === '"') { if (text[i + 1] === '"') { field += '"'; i++; } else q = false; }
      else field += c;
    } else if (c === '"') q = true;
    else if (c === ',') { row.push(field); field = ''; }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (c !== '\r') field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

// Rows -> deduped entries; a guid keeps its easiest level (easy files first).
export function buildVocab(fileRows, zh = {}) {
  const byGuid = new Map();
  for (const { level, rows } of fileRows) {
    const [header, ...data] = rows;
    const col = Object.fromEntries(header.map((h, i) => [h.trim(), i]));
    for (const r of data) {
      if (r.length < header.length) continue;
      const guid = r[col.guid];
      if (!guid) continue;
      const prev = byGuid.get(guid);
      if (prev && RANK[prev.level] <= RANK[level]) continue;
      const word = r[col.expression], reading = r[col.reading];
      byGuid.set(guid, {
        id: 'v:' + guid, word, reading, meaning: zh[guid] ?? r[col.meaning], level,
        furigana: alignFurigana(word, reading),
      });
    }
  }
  return [...byGuid.values()];
}

export function generate(dir) {
  const zhPath = path.join(dir, 'zh-tw.json');
  const zh = fs.existsSync(zhPath)
    ? JSON.parse(fs.readFileSync(zhPath, 'utf8')) : {};
  return buildVocab(FILES.map(([file, level]) => ({
    level, rows: parseCsv(fs.readFileSync(path.join(dir, file), 'utf8')),
  })), zh);
}

const isMain = process.argv[1] && fs.realpathSync(process.argv[1]) === import.meta.filename;
if (isMain) {
  const root = path.join(import.meta.dirname, '..');
  const vocab = generate(path.join(root, 'data', 'jlpt'));
  const out = '// GENERATED by scripts/gen-vocab.js — do not edit. Run: npm run gen:vocab\n'
    + `export const VOCAB = ${JSON.stringify(vocab)};\n`;
  fs.writeFileSync(path.join(root, 'src', 'vocab-data.js'), out);
  console.log('wrote src/vocab-data.js ·', vocab.length, 'entries');
}
